controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    # Adjust these joint names based on your actual Tugbot model
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    wheel_separation: 0.4
    wheel_radius: 0.1
    
    # Control parameters
    publish_rate: 50.0
    cmd_vel_topic: cmd_vel
    base_frame_id: base_link
    use_stamped_vel: false